name: Deploy pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.AWS_EC2_HOST}}
          key: ${{secrets.SERVER_SSH_KEY}}
          username: ubuntu
          script: |
            echo "deployment starting..."

            # Navigate to project directory
            cd fastapi-book-project
            git fetch --all
            git pull origin main
            python3 -m venv venv || exit 1
            source venv/bin/activate || exit 1
            python -m pip install --upgrade pip || exit 1
            pip install -r requirements.txt || exit 1

            # Stop existing application if running
            echo "Stopping existing application..."
            killall uvicorn || echo "No existing process found"
            echo "Application stopped successfully"

            # Start application
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
            echo "Application started successfully"